### ISSUE TITLE
docker build failure because of zip file corrupted

### ISSUE THREAD

**Issue by WxFang** [cathive/concourse-sonarqube-resource#26]
Days ago I rebuilt somarqube image using this Dockerfile and it worked fine.

But when I build it today, it failed at 

```
RUN curl -s -L "${SONAR_SCANNER_DOWNLOAD_URL}" > "/tmp/sonar-scanner-cli-3.2.0.1227-linux.zip" \
&& unzip -qq "/tmp/sonar-scanner-cli-3.2.0.1227-linux.zip" -d "/data" \
```
It returns error as below.
```
[/tmp/sonar-scanner-cli-3.2.0.1227-linux.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/sonar-scanner-cli-3.2.0.1227-linux.zip or
        /tmp/sonar-scanner-cli-3.2.0.1227-linux.zip.zip, and cannot find /tmp/sonar-scanner-cli-3.2.0.1227-linux.zip.ZIP, period.
```

Could anyone help me? Is this jar file corrupted?

**Comment by headcr4sh** [comment]
Seems strange. I will look into it...

**Comment by headcr4sh** [comment]
The download URL for the sonar-scanner has changed.
I am very, very confused, because the (SHA512) checksums have changed as well, even though the artifact *should* be the same...

* Old download URL: https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
* New download URL (according to docs from SonarSource): https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip

I'll change the download URL *and* I will incorporate a checksum verification to the Dockerfile -- something that is long overdue, I suppose...
